kafka-local-destination-settings:
  producerBootstrap: localhost:9092
  producerKeySer: org.apache.kafka.common.serialization.StringSerializer
  producerValSer: com.shamanthka.rl.model.ProductSerializer
  acks: all
  consumerBootstrap: localhost:9092
  consumerKeyDeSer: org.apache.kafka.common.serialization.StringDeserializer
  consumerValDeSer: com.shamanthka.rl.model.ProductDeserializer
  groupId: myGroupId
  topicName: myProductTopic